name: Update Settings JSON

on:
  repository_dispatch:
    types: [update-settings]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update settings.json
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "${{ github.event.client_payload.content }}" | base64 -d > settings.json
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add settings.json
          git commit -m "Update settings.json via settings.html"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
